version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: catalog-postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catalog_user -d catalog" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:latest'
    ports:
      - '6379'

volumes:
  postgres_data:
