services:
  postgres:
    image: postgres:15-alpine
    container_name: catalog-postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catalog_user -d catalog" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: catalog-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: product-catalog:latest
    container_name: catalog-app
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/catalog
      SPRING_R2DBC_USERNAME: catalog_user
      SPRING_R2DBC_PASSWORD: catalog_password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

volumes:
  postgres_data:
