spring:
  application:
    name: product-catalog-service

  datasource:
    url: r2dbc:postgresql://localhost:5432/catalog
    username: catalog_user
    password: catalog_password

  webflux:
    multipart:
      max-in-memory-size: 10MB
      max-disk-usage-per-part: 10MB
  http:
    codecs:
      max-in-memory-size: 10MB

server:
  port: 8080

logging:
  level:
    com.albert.catalog: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
