spring:
  application:
    name: product-catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog_user
    password: catalog_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      products:
        ttl: 30m
      productPages:
        ttl: 5m

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    com.albert.catalog: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
