spring:
  application:
    name: product-catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog_user
    password: catalog_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    com.albert.catalog: DEBUG
    org.springframework.web: DEBUG