spring:
  application:
    name: product-catalog-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/catalog
    username: catalog_user
    password: catalog_password

  flyway:
    url: jdbc:postgresql://localhost:5432/catalog
    user: catalog_user
    password: catalog_password
    schemas: catalog

  webflux:
    multipart:
      max-in-memory-size: 10MB
      max-disk-usage-per-part: 10MB
  http:
    codecs:
      max-in-memory-size: 10MB

server:
  port: 8080

logging:
  level:
    com.albert.catalog: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
