CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TABLE IF NOT EXISTS catalog.products
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid       UUID      NOT NULL UNIQUE,
    gold_id          BIGINT       NOT NULL UNIQUE,
    long_name        VARCHAR(255) NOT NULL,
    short_name       VARCHAR(155) NOT NULL,
    iow_unit_type    VARCHAR(100) NOT NULL,
    healthy_category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version    BIGINT    NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_products_gold_id ON catalog.products (gold_id);
